[package]
name = "rust-crud" # 🦀🦀🦀🦀
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
dotenv = "0.15.0"
futures = "0.3.28"
tokio = "1.28.2"
pretty_env_logger = "0.5.0"
mongodb = "2.5.0"
serde = { version = "1.0.163", features = ["derive"] }
